services:
  db:
    image: postgres:9.4
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: votes
    ports:
      - '5432:5432'
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - postgres-net
      - worker-net

  redis:
    image: redis:5.0-alpine3.10
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-net
      - worker-net

  vote:
    build: 
      context: ./vote
      dockerfile: Dockerfile
    container_name: vote-app
    ports:
      - "8080:80"
    depends_on:
      - redis
    networks:
      - redis-net

  result:
    build: 
      context: ./result
      dockerfile: Dockerfile
    container_name: result-app
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - postgres-net

  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker-app
    depends_on:
      - db
      - redis
    networks:
      - worker-net


volumes:
  local_pgdata:

networks:
  worker-net:
  postgres-net:
  redis-net:
